symbol: "BTCUSDT"
interval: "4h"
start_date: "1 Jan 2020"
fee: 0.002   

backW: [1,2,3,4,5]
forW:  [1,2,3,4,5]

calibration_mode: "exact_paper"
single_candle_percentiles:
  alpha_pct: 0.25
  beta_pct: 0.997
scale_beta_per_step: 0.10